build-optimized:
	g++ -std=c++23 -O3 -o main main.cpp data-generator.cpp algorithms.cpp data-structures.cpp csv.cpp

build:
	g++ -std=c++23 -O0 -o main main.cpp data-generator.cpp algorithms.cpp data-structures.cpp csv.cpp
