build-optimized:
	g++ -std=c++23 -O3 -o main main.cpp data-generator.cpp algorithms-part-1.cpp algorithms-part-2.cpp algorithms-part-3.cpp

build:
	g++ -std=c++23 -O0 -o main main.cpp data-generator.cpp algorithms-part-1.cpp algorithms-part-2.cpp algorithms-part-3.cpp
